CREATE TABLE Logs (
    LogId INT IDENTITY PRIMARY KEY,
    LogLevel NVARCHAR(50),
    EventCode NVARCHAR(100),
    CorrelationId UNIQUEIDENTIFIER,
    UserMessage NVARCHAR(MAX),
    TechnicalDetails NVARCHAR(MAX),
    CreatedAt DATETIMEOFFSET DEFAULT SYSDATETIMEOFFSET()
)
